steps:

- name: 'ubuntu'
  args: ['echo', 'hello world, after  ${_TEST} s and a secret from ']
  secretEnv: ['PASSWORD']
availableSecrets:
  secretManager:
  - versionName: projects/522701491256/secrets/PASS/versions/latest
    env: 'PASSWORD'

