steps:

- name: 'ubuntu'
  args: ['echo', 'hello world, after  ${_TEST} s and a secret from ']
  secretEnv: ['MYTEST']
availableSecrets:
  secretManager:
  - versionName: projects/delete-328822/secrets/test/versions/latest
    env: "MYTEST"


