steps:


  - name: gcr.io/cloud-builders/curl
  entrypoint: bash
  args: 
    - "-c"
    - |
      echo "{\"body\": \"Preview this revision: $(cat /workspace/url.txt)\"}" > /workspace/api_payload.txt && \
      curl -s -H "Authorization: token $$GITHUB_TOKEN" -X POST -d @/workspace/api_payload.txt "https://api.github.com/repos/davidstanke/stanke.dev/issues/$_PR_NUMBER/comments"
  secretEnv: 
    - GITHUB_TOKEN